module.exports = (sequelize, DataTypes) => {
  const Background = sequelize.define("Background", {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      _autoGenerated: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  });

  return Background;
};
