module.exports = (sequelize, DataTypes) => {
  const MediaGenre = sequelize.define("MediaGenre", {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      _autoGenerated: true
    },
    mediaId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    genreId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  });

  return MediaGenre;
};
