module.exports = (sequelize, DataTypes) => {
  const MediaTheme = sequelize.define("MediaTheme", {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      _autoGenerated: true
    },
    mediaId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    themeId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  });

  return MediaTheme;
};
