module.exports = (sequelize, DataTypes) => {
  const MediaType = sequelize.define("MediaType", {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      _autoGenerated: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  });

  return MediaType;
};
